### ISSUE TITLE
The green blinking on save quickly gets annoying

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/hoverpad#10]
Though useful for being notified that things were properly saved (so we should keep the feature), it could probably be less invasive and more discreet. How about a tiny spinner icon turning into a green check mark once properly saved (and into a red cross when something failed for some reason)?

**Comment by mostlygeek** [comment]
@ryanfeeley this is what the green blinking is :)

**Comment by Natim** [comment]
This was fixed in master.
