### ISSUE TITLE
Make a full Firefox toolbar icon

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-services/hoverpad#20]
All the states accounted for, just like a real Firefox toolbar icon!
File names should make sense.
[Toolbar.zip](https://github.com/mozilla-services/hoverpad/files/772429/Toolbar.zip)

**Comment by Natim** [comment]
Do you have an example of how to pick the right one with regards to the skin in the add-on?
Do you have icons for the toolbar of the add-on? Blur, Toggle Passwords and Gear menu?

**Comment by Natim** [comment]
Do you have a better resolution of those buttons? 16px seems a bit low for me to use.

**Comment by ryanfeeley** [comment]
@Natim Do Web Extensions limit us to the same icon for the toolbar as in the menu?

Here are 48px and 96px PNGs.

A little disappointed this won't look like a real Firefox icon (where the icons vary by platform)
![universal-notepad-48](https://cloud.githubusercontent.com/assets/68213/24167403/078d8272-0e4d-11e7-8b94-127c871148db.png)
![universal-notepad-96](https://cloud.githubusercontent.com/assets/68213/24167448/2b80ed54-0e4d-11e7-8ce7-3bf6f19bfa21.png)

**Comment by Natim** [comment]
Yes we should take your feedback to the WebExtension team.
