### ISSUE TITLE
Add Circle-CI for running tests/linting on each commit

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/hoverpad#26]
We actually have a pretty beautiful setup over on the [**mozilla/pulse**](https://github.com/mozilla/pulse/blob/master/circle.yml) repo where we build the XPI on Circle-CI and then copy it into the `$CIRCLE_ARTIFACTS` directory so you can grab the XPI for each run from the Circle-CI site [if you're logged in].

But at a minimum, we should build the add-on for each commit and make sure we're running ESLint and whatever other linters we want.

**Comment by magopian** [comment]
Should we also build the desktop applications (using electron-packager)?

Curious as to why we should use Circle-CI over Travis. I've used both, and haven't seen much of a difference, did I miss something?

**Comment by pdehaan** [comment]
> Should we also build the desktop applications (using electron-packager)?

Probably. It'd be nice to make sure nothing breaks the desktop apps. Plus, we can copy those installers into the `$CIRCLE_ARTIFACTS` as well so you can download them per build.

> Curious as to why we should use Circle-CI over Travis. I've used both, and haven't seen much of a difference, did I miss something?

I don't know why we prefer one over the other. I think Circle-CI is what OPs prefers. I'm fine with either, just as long as we're using some sort of CI to run tests and linting the code.
