### ISSUE TITLE
Document how the extensions are built, and (self-)signed

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/hoverpad#36]
> @Natim: I usually use the `manifest-demo.json` to build the self-signed extension because it can take a long time before being reviewed on AMO. And I am changing the version number by end before doing so.
> &mdash; via https://github.com/mozilla-services/hoverpad/issues/32#issuecomment-282965768

> @magopian: Can you comment (or document somewhere) how the extensions are built, and (self-)signed please?
> &mdash; via https://github.com/mozilla-services/hoverpad/issues/32#issuecomment-282967883

**Comment by pdehaan** [comment]
Oops, I'm not a repo collaborator here, so somebody else will need to assign @Natim.

**Comment by magopian** [comment]
done! Thanks for filing ;)
