### ISSUE TITLE
Add the FxA Login Flow (See how it was done for Pocket)

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/hoverpad#4]
If the user is not signed into FxA should we put a notice on the UI to show that their data won't be synced?

**Comment by Natim** [comment]
1. Click on a link that will open a tab with the form
2. The redirect url is on a known domain name we can watch it in order to grab the token

See: https://gist.github.com/Natim/447c3293ab5c0996687ccead0d48b143

**Comment by Natim** [comment]
Done in #38
