### ISSUE TITLE
Sometimes a small popup appears

### ISSUE THREAD

**Issue by ianb** [mozilla-services/hoverpad#48]
On Chrome, after installation and with a passphrase but no login, I sometimes get this popup:

![image](https://cloud.githubusercontent.com/assets/44390/24316033/fb74d65c-10b8-11e7-945c-074b0c7fd94e.png)

Seems to happen about half the time.  When it does happen, the full edit window flashes up and then is replaced with this window.

**Comment by Natim** [comment]
I think we need to define a min-height then thanks for reporting.
