### ISSUE TITLE
How great it is

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-services/hoverpad#53]
- [ ] To-do
- [ ] List interface
- [x] great?
- [x] You can
- [x] do what
- [ ] ever it is
- [x] Isn't this
- [x] you want
- [ ] to do
- [ ] with items

**Comment by ryanfeeley** [comment]
Although doesn't work at all on mobile

**Comment by vladikoff** [comment]
what is happening in this issue @ryanfeeley 😄

**Comment by ryanfeeley** [comment]
Nothing we can delete/close it. Just playin’.

**Comment by vladikoff** [comment]
:)
