### ISSUE TITLE
FxA pop-up does not scroll

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla-services/hoverpad#54]
STEPS TO REPRODUCE
1. Open FxA window for Hoverpad
2. Resize it

EXCEPTED RESULTS
- It should scroll if content overflows

ACTUAL RESULTS
- It don't

**Comment by Natim** [comment]
I was a bit confused to see a popup for this flow, can't we use a tab instead?

**Comment by vladikoff** [comment]
Sadly we cannot use the tab, limitation of the identity api

**Comment by vladikoff** [comment]
I filed a bugzilla bug about scrolling: https://bugzilla.mozilla.org/show_bug.cgi?id=1369257
