### ISSUE TITLE
Copy Pasting inserts extra returns :(

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/hoverpad#56]
<img width="381" alt="screen shot 2017-07-07 at 4 20 09 pm" src="https://user-images.githubusercontent.com/3323249/27975452-32c14ee6-6330-11e7-84a8-40f2e086b3a4.png">

becomes
```
notSupportedHeader = Your browser is not supported.

notSupportedHeader = Unfortunately this browser does not support the web technology that powers Firefox Send. You'll need to try another browser. We recommend Firefox!

// Note Firefox name should not be localized in button, but subhead should

downloadFirefoxButtonSub = Free Download

// note the sentence lower on this page is the same as uploadPageExplainer. Also the link on this page should be removed as Send wont work on this browser anyway
```

when copy pasted

**Comment by johngruen** [comment]
@vladikoff i'm on 1.4. I'd consider this a blocker since copy/pasting is currently the only way to extract content from notes

**Comment by Natim** [comment]
Are you using [hoverpad](https://github.com/mozilla-services/hoverpad) or [notes](https://github.com/mozilla/notes)?

**Comment by johngruen** [comment]
haha oops.

**Comment by vladikoff** [comment]
👍
