### ISSUE TITLE
Ensure that metrics are not sent if DNT is enabled.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla-services/hoverpad#57]
You can detect this in a [background page](https://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/background) by inspecting `navigator.doNotTrack`.

**Comment by vladikoff** [comment]
Should be here: https://github.com/mozilla/notes/issues/140

**Comment by pdehaan** [comment]
@vladikoff Should we kill this repo if it's no longer "active"? Or maybe rename it to "hoverpad_retired" so we break old links.

**Comment by chuckharmston** [comment]
Yes please. Of note: if you use Github to rename a repo, it will set up redirects to the new names.

**Comment by Natim** [comment]
Well there are two distincts extensions, hoverpad opens a notepad in the popup while notes open it in the sidebar.

**Comment by Natim** [comment]
I have updated the README to talk about that: https://github.com/mozilla-services/hoverpad/blob/master/README.md
